---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-svc"
spec:
  selector:
    app: travel-talk-ui
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
