---
image: ghcr.io/traveltransporttalk/traveltalk:latest
apiBaseUrl: "http://travel-talk-server-svc:8080/tt/"

ingress:
  enabled: true
  className: nginx
  tls:
    enabled: true
    secretName: travel-talk-mkls-space
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - travel-talk.mkls.space
