---
image: ghcr.io/traveltransporttalk/traveltalk:latest
apiBaseUrl: "https://travel-talk.mkls.space/tt"

ingress:
  enabled: true
  className: nginx
  tls:
    enabled: true
    secretName: travel-talk-mkls-space
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - travel-talk.mkls.space
